backend:
  name: github
  repo: lostfictions/barf

media_folder: public/uploads  # Media files will be stored in the repo under public/uploads
public_folder: /uploads # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "copy/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "copy/why-unionize/index.md"
        label: "Why Unionize?"
        name: "why-unionize"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages-fr"
    label: "Pages (français)"
    files:
      - file: "copy/home/index-fr.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "copy/why-unionize/index-fr.md"
        label: "Why Unionize?"
        name: "why-unionize"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
